class ReferenceError(Exception):
    pass

class TypeError(Exception):
    pass

class ValueError(Exception):
    pass

class InternalError(Exception):
    pass
